#!/usr/bin/env python3
"""Synchronize standard toolchain files from versions selected by Nix."""

from __future__ import annotations

import argparse
import difflib
import json
from pathlib import Path
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--rust", required=True)
    parser.add_argument("--flutter", required=True)
    parser.add_argument("--java", required=True)
    parser.add_argument("--cargo-ndk", required=True)
    parser.add_argument("--android-platform", required=True)
    parser.add_argument("--android-compile-sdk", required=True)
    parser.add_argument("--android-compile-sdk-minor", required=True)
    parser.add_argument("--android-build-tools", required=True)
    parser.add_argument("--android-ndk", required=True)
    parser.add_argument("--android-cmdline-tools", required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating files when a mirror is stale",
    )
    return parser.parse_args()


def rendered_files(args: argparse.Namespace) -> dict[str, str]:
    fvmrc = {
        "flutter": args.flutter,
        "updateVscodeSettings": False,
    }
    return {
        ".fvmrc": json.dumps(fvmrc, indent=2) + "\n",
        "rust-toolchain.toml": (
            "# Generated by `nix run .#sync-toolchains`; edit flake inputs instead.\n"
            "[toolchain]\n"
            f'channel = "{args.rust}"\n'
            'profile = "minimal"\n'
            'components = ["rust-src"]\n'
        ),
        ".java-version": args.java + "\n",
        "android/toolchain.properties": (
            "# Generated by `nix run .#sync-toolchains`; edit flake inputs instead.\n"
            f"android.platform={args.android_platform}\n"
            f"android.compileSdk={args.android_compile_sdk}\n"
            f"android.compileSdkMinor={args.android_compile_sdk_minor}\n"
            f"android.targetSdk={args.android_compile_sdk}\n"
            f"android.buildTools={args.android_build_tools}\n"
            f"android.ndk={args.android_ndk}\n"
            f"android.cmdlineTools={args.android_cmdline_tools}\n"
            f"cargoNdk={args.cargo_ndk}\n"
        ),
    }


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    stale = False

    for relative_path, expected in rendered_files(args).items():
        path = root / relative_path
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue

        if args.check:
            stale = True
            print(f"{relative_path} is out of sync with the locked Nix toolchain:")
            print(
                "".join(
                    difflib.unified_diff(
                        actual.splitlines(keepends=True),
                        expected.splitlines(keepends=True),
                        fromfile=relative_path,
                        tofile=f"{relative_path} (expected)",
                    )
                ),
                end="",
            )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
            print(f"updated {relative_path}")

    if stale:
        print("Run `nix run .#sync-toolchains` to update the mirrors.", file=sys.stderr)
        return 1
    if args.check:
        print("Toolchain mirrors match the locked Nix package set.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
