// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<void> initializeRustDiagnostics({required String filter}) => RustLib
    .instance
    .api
    .crateApiDiagnosticsInitializeRustDiagnostics(filter: filter);

Future<void> setRustDiagnosticFilter({required String filter}) => RustLib
    .instance
    .api
    .crateApiDiagnosticsSetRustDiagnosticFilter(filter: filter);

Stream<RustDiagnosticBatch> createRustDiagnosticStream() =>
    RustLib.instance.api.crateApiDiagnosticsCreateRustDiagnosticStream();

class RustDiagnosticBatch {
  final List<RustDiagnosticEvent> events;

  const RustDiagnosticBatch({required this.events});

  @override
  int get hashCode => events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDiagnosticBatch &&
          runtimeType == other.runtimeType &&
          events == other.events;
}

class RustDiagnosticEvent {
  final PlatformInt64 timestampMillis;
  final BigInt sourceSequence;
  final String level;
  final String module;
  final String rawTarget;
  final String eventCode;
  final String message;
  final Map<String, String> fields;
  final bool consoleAlreadyReported;

  const RustDiagnosticEvent({
    required this.timestampMillis,
    required this.sourceSequence,
    required this.level,
    required this.module,
    required this.rawTarget,
    required this.eventCode,
    required this.message,
    required this.fields,
    required this.consoleAlreadyReported,
  });

  @override
  int get hashCode =>
      timestampMillis.hashCode ^
      sourceSequence.hashCode ^
      level.hashCode ^
      module.hashCode ^
      rawTarget.hashCode ^
      eventCode.hashCode ^
      message.hashCode ^
      fields.hashCode ^
      consoleAlreadyReported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDiagnosticEvent &&
          runtimeType == other.runtimeType &&
          timestampMillis == other.timestampMillis &&
          sourceSequence == other.sourceSequence &&
          level == other.level &&
          module == other.module &&
          rawTarget == other.rawTarget &&
          eventCode == other.eventCode &&
          message == other.message &&
          fields == other.fields &&
          consoleAlreadyReported == other.consoleAlreadyReported;
}
