// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `handle_connection`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FORWARD_SERVERS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `deref`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

/// 创建并启动一个端口转发服务器
/// 返回服务器索引，用于后续操作
Future<BigInt> createForwardServer({
  required String listenAddr,
  required String forwardAddr,
}) => RustLib.instance.api.crateApiForwardCreateForwardServer(
  listenAddr: listenAddr,
  forwardAddr: forwardAddr,
);

/// 停止指定索引的端口转发服务器
Future<void> stopForwardServer({required BigInt index}) =>
    RustLib.instance.api.crateApiForwardStopForwardServer(index: index);

/// 停止所有端口转发服务器
Future<void> stopAllForwardServers() =>
    RustLib.instance.api.crateApiForwardStopAllForwardServers();

/// 获取指定服务器的统计信息
Future<(BigInt, BigInt, BigInt)> getForwardServerStats({
  required BigInt index,
}) => RustLib.instance.api.crateApiForwardGetForwardServerStats(index: index);

/// 获取所有正在运行的服务器数量
Future<BigInt> getForwardServerCount() =>
    RustLib.instance.api.crateApiForwardGetForwardServerCount();

/// 检查指定服务器是否正在运行
Future<bool> isForwardServerRunning({required BigInt index}) =>
    RustLib.instance.api.crateApiForwardIsForwardServerRunning(index: index);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ForwardServer>>
abstract class ForwardServer implements RustOpaqueInterface {
  ServerStats get stats;

  set stats(ServerStats stats);

  Future<bool> isRunning();

  Future<void> start();

  Future<void> stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ServerStats>>
abstract class ServerStats implements RustOpaqueInterface {
  Future<BigInt> getBytesReceived();

  Future<BigInt> getBytesSent();

  Future<BigInt> getConnections();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ServerStats> newInstance() =>
      RustLib.instance.api.crateApiForwardServerStatsNew();
}
