// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MULTICAST_SENDERS`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`, `with_bind_addr`

/// 创建并启动一个组播发送器
/// 返回发送器索引，用于后续操作
Future<BigInt> createMulticastSender({
  required String multicastAddr,
  required int port,
  required List<int> data,
  required BigInt intervalMs,
}) => RustLib.instance.api.crateApiMulticastCreateMulticastSender(
  multicastAddr: multicastAddr,
  port: port,
  data: data,
  intervalMs: intervalMs,
);

/// 创建并启动一个组播发送器（带自定义绑定地址）
Future<BigInt> createMulticastSenderWithBind({
  required String multicastAddr,
  required int port,
  required String bindAddr,
  required List<int> data,
  required BigInt intervalMs,
}) => RustLib.instance.api.crateApiMulticastCreateMulticastSenderWithBind(
  multicastAddr: multicastAddr,
  port: port,
  bindAddr: bindAddr,
  data: data,
  intervalMs: intervalMs,
);

/// 停止指定索引的组播发送器
Future<void> stopMulticastSender({required BigInt index}) =>
    RustLib.instance.api.crateApiMulticastStopMulticastSender(index: index);

/// 停止所有组播发送器
Future<void> stopAllMulticastSenders() =>
    RustLib.instance.api.crateApiMulticastStopAllMulticastSenders();

/// 获取所有正在运行的组播发送器数量
Future<BigInt> getMulticastSenderCount() =>
    RustLib.instance.api.crateApiMulticastGetMulticastSenderCount();

/// 检查指定发送器是否正在运行
Future<bool> isMulticastSenderRunning({required BigInt index}) => RustLib
    .instance
    .api
    .crateApiMulticastIsMulticastSenderRunning(index: index);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MulticastSender>>
abstract class MulticastSender implements RustOpaqueInterface {
  Future<bool> isRunning();

  Future<void> start();

  Future<void> stop();
}
