// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_udp_stun_server_list`, `create_binding_request`, `detect_nat_type_ipv4`, `is_success_stun_response`, `map_easy_nat_type`, `normalize_stun_server`, `test_udp_ipv4`, `test_udp_ipv6`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// NAT test entry for Flutter.
Future<NetworkTestResult> testNetworkConnectivity({
  required String stunServer,
}) => RustLib.instance.api.crateApiNatTestTestNetworkConnectivity(
  stunServer: stunServer,
);

/// Backward-compatible API: detect IPv4 NAT type.
Future<String> detectNatType({required String stunServer}) =>
    RustLib.instance.api.crateApiNatTestDetectNatType(stunServer: stunServer);

enum NatType {
  openInternet,
  fullCone,
  restrictedCone,
  portRestrictedCone,
  symmetric,
  symmetricUdpFirewall,
  blocked,
  unknown;

  Future<String> getDescription() =>
      RustLib.instance.api.crateApiNatTestNatTypeGetDescription(that: this);
}

class NetworkTestResult {
  final String natTypeV4;
  final String natTypeV6;
  final PlatformInt64 ipv4Latency;
  final PlatformInt64 ipv6Latency;

  const NetworkTestResult({
    required this.natTypeV4,
    required this.natTypeV6,
    required this.ipv4Latency,
    required this.ipv6Latency,
  });

  @override
  int get hashCode =>
      natTypeV4.hashCode ^
      natTypeV6.hashCode ^
      ipv4Latency.hashCode ^
      ipv6Latency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTestResult &&
          runtimeType == other.runtimeType &&
          natTypeV4 == other.natTypeV4 &&
          natTypeV6 == other.natTypeV6 &&
          ipv4Latency == other.ipv4Latency &&
          ipv6Latency == other.ipv6Latency;
}
