// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These functions are ignored because they are not marked as `pub`: `get_instance_info`, `parse_instance_id`, `peer_conn_info_to_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MANAGER`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

Future<void> sendUdpToLocalhost({required String message}) =>
    RustLib.instance.api.crateApiP2PSendUdpToLocalhost(message: message);

Future<JoinHandle> handleEvent({required EventBusSubscriber events}) =>
    RustLib.instance.api.crateApiP2PHandleEvent(events: events);

Future<String> easytierVersion() =>
    RustLib.instance.api.crateApiP2PEasytierVersion();

Future<bool> isEasytierRunning({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PIsEasytierRunning(instanceId: instanceId);

Future<List<String>> getIps({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetIps(instanceId: instanceId);

Future<void> setTunFd({required String instanceId, required int fd}) =>
    RustLib.instance.api.crateApiP2PSetTunFd(instanceId: instanceId, fd: fd);

Future<String> getRunningInfo({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetRunningInfo(instanceId: instanceId);

Future<JoinHandleResultStringString> createServer({
  required String configToml,
  required bool watchEvent,
}) => RustLib.instance.api.crateApiP2PCreateServer(
  configToml: configToml,
  watchEvent: watchEvent,
);

Future<JoinHandleResultStringString> createServerWithFlags({
  required String username,
  required bool enableDhcp,
  required String specifiedIp,
  required String roomName,
  required String roomPassword,
  required List<String> severurl,
  required List<String> onurl,
  required List<String> cidrs,
  required List<Forward> forwards,
  required FlagsC flag,
}) => RustLib.instance.api.crateApiP2PCreateServerWithFlags(
  username: username,
  enableDhcp: enableDhcp,
  specifiedIp: specifiedIp,
  roomName: roomName,
  roomPassword: roomPassword,
  severurl: severurl,
  onurl: onurl,
  cidrs: cidrs,
  forwards: forwards,
  flag: flag,
);

Future<void> closeServer({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PCloseServer(instanceId: instanceId);

Future<List<PeerRoutePair>> getPeerRoutePairs({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetPeerRoutePairs(instanceId: instanceId);

Future<KVNetworkStatus> getNetworkStatus({required String instanceId}) =>
    RustLib.instance.api.crateApiP2PGetNetworkStatus(instanceId: instanceId);

Future<void> initApp() => RustLib.instance.api.crateApiP2PInitApp();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventBusSubscriber>>
abstract class EventBusSubscriber implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< JoinHandle < () >>>
abstract class JoinHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JoinHandle < Result < String , String > >>>
abstract class JoinHandleResultStringString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PeerRoutePair>>
abstract class PeerRoutePair implements RustOpaqueInterface {}
